import { Project } from './models';

export const CATEGORIES = [
  'Tout', 'Couture', 'Crochet',
  'Décoration', 'Fleurs', 'Maquillage FX', 'Coiffure'
];

export const PROJECTS: Project[] = [
  {
    id: 'corset',
    title: 'Corset bustier en dentelle noire',
    category: 'Couture',
    image: '/assets/corset-mannequin-front.jpeg',
    images: [
      '/assets/corset-mannequin-front.jpeg',
      '/assets/corset-mannequin-cote.jpeg',
      '/assets/corset-mannequin-dos.jpeg',
      '/assets/corset-plat.jpeg',
    ],
    description: 'Corset bustier cousu entièrement à la main, en dentelle florale noire doublée avec baleines et laçage satin.',
    materials: 'Dentelle florale noire, tissu noir, baleines plastique, coque',
    story: `C'est mon deuxième projet de couture, mais le premier vraiment complexe. J'ai tout réalisé sans machine à coudre — chaque point a été fait à la main, ce qui demande beaucoup de patience et de précision, surtout sur de la dentelle. Les tissus ont été achetés en mercerie, et j'ai dû adapter le montage au fur et à mesure pour intégrer les baleines et la coque correctement. Ce projet m'a appris énormément sur la construction d'un vêtement structuré.`,
  },
  {
    id: 'pochettes-crochet',
    title: 'Pochettes en fil chenille (lot de 3)',
    category: 'Crochet',
    image: '/assets/pochettes-chenille-trio.jpeg',
    images: [
      '/assets/pochettes-chenille-trio.jpeg',
    ],
    description: 'Trio de pochettes crochetées en fil chenille, déclinées en trois tailles avec bouton de récupération.',
    materials: 'Fil chenille, boutons de récupération',
    story: `Ces trois pochettes sont réalisées avec un crochet n°8 à partir d'un même point de départ : un granny square plié sur lui-même pour former une pochette. Le fil chenille, très doux au toucher, donne un rendu texturé et agréable. En répétant la même forme en trois tailles différentes, j'ai pu créer un ensemble cohérent et modulable. Les boutons, tous issus de récupération, ajoutent une touche unique à chaque pièce.`,
  },
  {
    id: 'citrouille',
    title: 'Citrouille sculptée pour Halloween',
    category: 'Décoration',
    image: '/assets/citrouille-halloween.jpeg',
    images: [
      '/assets/citrouille-halloween.jpeg',
    ],
    description: 'Citrouille évidée et sculptée à la main, illuminée de l\'intérieur par une bougie LED.',
    materials: 'Citrouille naturelle, bougie LED',
    story: `Pour Halloween, nous avons voulu décorer la maison avec des citrouilles faites maison. Après avoir évidé la citrouille, j'ai sculpté un motif directement dans la chair à l'aide d'outils de cuisine. Une bougie LED placée à l'intérieur crée un effet lumineux qui met en valeur le motif découpé une fois la nuit tombée.`,
  },
  {
    id: 'maquillage-ca-clown',
    title: 'Maquillage Ça — clown d\'horreur',
    category: 'Maquillage FX',
    image: '/assets/maquillage-ca-clown.jpeg',
    images: [
      '/assets/maquillage-ca-clown.jpeg',
    ],
    description: 'Maquillage inspiré du clown Ça, réalisé sur la moitié d\'un visage avec cicatrice en latex.',
    materials: 'Latex liquide, papier mouchoir, peinture pour visage, faux sang, sang coagulé',
    story: `Réalisé pour Halloween 2025 sur une amie. L'idée était de recréer l'esthétique du clown Ça sur une seule moitié du visage, pour un effet de contraste saisissant. Pour la cicatrice centrale, j'ai appliqué du latex sur du papier mouchoir afin d'accélérer le séchage et d'améliorer la tenue. Je ne suis pas entièrement satisfaite du résultat : le sang coagulé utilisé n'était pas de bonne qualité et n'a pas rendu comme prévu. Une expérience qui m'a donné envie de tester de meilleurs produits à l'avenir.`,
  },
  {
    id: 'main-ensanglantee',
    title: 'Main ensanglantée — test latex et papier',
    category: 'Maquillage FX',
    image: '/assets/main-ensanglantee-test-latex.jpeg',
    images: [
      '/assets/main-ensanglantee-test-latex.jpeg',
    ],
    description: 'Test de maquillage FX sur la main avec égratignures simulées en latex et papier.',
    materials: 'Latex liquide, faux sang, sang coagulé, fard gras noir, papier mouchoir',
    story: `Avant de réaliser un maquillage sur quelqu'un pour Halloween, j'ai voulu tester l'efficacité du latex avec du papier mouchoir directement sur ma propre main. Le latex liquide seul sèche très lentement — c'est l'un des problèmes majeurs dans les maquillages FX. En incorporant du papier mouchoir dans les couches, j'ai constaté qu'on passait de 3 à 5 couches nécessaires à seulement 2, ce qui réduit significativement le temps global de réalisation. Le séchage couche par couche reste long, mais le gain en épaisseur et en solidité m'a convaincue d'adopter cette technique pour mes prochains maquillages.`,
  },
  {
    id: 'sac-tshirt-kaki',
    title: 'Sac bandoulière en fil t-shirt kaki',
    category: 'Crochet',
    image: '/assets/sac-tshirt-kaki.jpeg',
    images: [
      '/assets/sac-tshirt-kaki.jpeg',
    ],
    description: 'Petit sac bandoulière crocheté en fil t-shirt kaki, solide et structuré.',
    materials: 'Fil t-shirt kaki, crochet n°10',
    story: `Ce sac a été réalisé avec un crochet n°10 et du fil t-shirt kaki. Contrairement au fil coton ou au fil chenille — qui donnent des pièces très souples — le fil t-shirt produit un résultat bien plus rigide et structuré. Pour un sac, cette rigidité est un vrai avantage : le sac tient debout, garde sa forme et résiste à l'usure quotidienne. C'est ce qui m'a convaincue que ce type de fil est particulièrement adapté aux accessoires de ce genre.`,
  },
  {
    id: 'top-degrade-bleu',
    title: 'Top d\'été en dégradé bleu-violet',
    category: 'Crochet',
    image: '/assets/top-degrade-bleu-front.jpeg',
    images: [
      '/assets/top-degrade-bleu-front.jpeg',
      '/assets/top-degrade-bleu-dos.jpeg',
    ],
    description: 'Petit top d\'été crocheté en coton dégradé bleu et violet, avec bretelles fines réglables et boutons de récupération.',
    materials: 'Fil coton changeant de couleur, crochet n°2.5, boutons de récupération',
    story: `Ce top a été réalisé avec une pelote de coton qui change de couleur automatiquement, créant un dégradé naturel entre le bleu et le violet sans intervention particulière. Les bretelles, très fines, sont réglables pour un meilleur ajustement. Les boutons sur le devant — tous différents car issus de récupération — apportent une touche décalée et personnelle. Un projet estival qui m'a permis d'explorer les finitions et les fermetures au crochet.`,
  },
  {
    id: 'top-granny-square',
    title: 'Top granny square avec laçage dos',
    category: 'Crochet',
    image: '/assets/top-granny-square-front.jpeg',
    images: [
      '/assets/top-granny-square-front.jpeg',
      '/assets/top-granny-square-cote.jpeg',
    ],
    description: 'Top d\'été crocheté en granny squares et pentagones, avec laçage tressé tricolore dans le dos.',
    materials: 'Fil coton/bambou (1 pelote rose, 1 blanche, 1 marron), crochet n°4',
    story: `Ce top est construit à partir de granny squares et de pentagones (à cinq côtés) assemblés avec un crochet n°4. La taille est formée d'une rangée de cinq carrés, tandis que la poitrine est composée de trois pentagones par côté qui se rejoignent au centre, créant un galbe naturel par la forme des pièces elles-mêmes. Le laçage dans le dos est une tresse réalisée avec les trois couleurs de fils entrelacées, ce qui lui donne un aspect artisanal et soigné.`,
  },
  {
    id: 'top-vert-premier',
    title: 'Premier top crocheté — vert laçage dos',
    category: 'Crochet',
    image: '/assets/top-vert-front.jpeg',
    images: [
      '/assets/top-vert-front.jpeg',
      '/assets/top-vert-dos-lacage.jpeg',
    ],
    description: 'Premier projet de crochet : top vert avec bretelles fines et laçage dans le dos.',
    materials: 'Laine polyester verte, crochet n°5',
    story: `C'est le tout premier projet de crochet que j'ai réalisé. Avec le recul, la laine polyester choisie n'était pas idéale : elle tient chaud, la matière n'est pas agréable au toucher et ne respire pas bien. Mais ce projet m'a permis d'apprendre les bases. Les bretelles très fines forment un laçage dans le dos, une technique que j'ai ensuite réutilisée sur d'autres pièces en l'améliorant.`,
  },
  {
    id: 'roses-lumineuses',
    title: 'Roses lumineuses en ruban satin',
    category: 'Fleurs',
    image: '/assets/roses-lumineuses-led.jpeg',
    images: [
      '/assets/roses-lumineuses-led.jpeg',
      '/assets/roses-ruban-satin-detail.jpeg',
    ],
    description: 'Boîte de 8 roses en ruban satin rouge pailleté, illuminées par une guirlande LED.',
    materials: 'Ruban satin rouge, guirlande LED, boîte, mousse florale, paillettes',
    story: `Pour les 20 ans de mon amie, je voulais lui offrir des fleurs — mais des fleurs qui durent. J'ai fabriqué chaque rose à la main en découpant puis en pliant et collant du ruban satin pour former les pétales. Des paillettes ont été ajoutées pour apporter de l'éclat, et une guirlande LED disposée sous les fleurs illumine l'ensemble depuis la boîte. Un cadeau à la fois décoratif et personnel, qui garde toute sa beauté longtemps après l'anniversaire.`,
  },
  {
    id: 'grinch-perles',
    title: 'Main du Grinch en perles à repasser',
    category: 'Décoration',
    image: '/assets/grinch-perles-sapin.jpeg',
    images: [
      '/assets/grinch-perles-sapin.jpeg',
    ],
    description: 'Décoration de sapin représentant la main du Grinch tenant une boule de Noël, en perles à repasser.',
    materials: 'Perles à repasser vertes, rouges, blanches et noires',
    story: `Grande fan du Grinch, j'ai voulu intégrer ce personnage culte dans la décoration de notre sapin de Noël. J'ai reproduit sa main iconique tenant une boule de Noël en perles à repasser, puis thermosoudé l'ensemble au fer. Une fois accroché dans le sapin, il ajoute une touche d'humour et de nostalgie à la décoration. Simple à réaliser mais très efficace visuellement.`,
  },
  {
    id: 'alice-carte-2024',
    title: 'Alice au Pays des Merveilles — carte dans la tête',
    category: 'Maquillage FX',
    image: '/assets/alice-carte-2024.jpeg',
    images: [
      '/assets/alice-carte-2024.jpeg',
    ],
    description: 'Maquillage Halloween 2024 : illusion d\'une carte de la Reine de Cœur enfoncée dans le crâne.',
    materials: 'Carte à jouer, faux sang, sang coagulé, latex liquide',
    story: `Pour Halloween 2024, j'ai maquillé mon amie en Alice au Pays des Merveilles avec une touche gore. Nous avons choisi de simuler l'illusion d'une carte enfoncée dans sa tête — et pas n'importe laquelle : la Reine de Cœur, en référence directe au personnage antagoniste du film. Le latex a été utilisé pour créer les bords de la plaie autour de la carte, avec du faux sang et du sang coagulé pour le rendu réaliste.`,
  },
  {
    id: 'blessures-lian-laya',
    title: 'Blessures maquillées — Lina & Laya',
    category: 'Maquillage FX',
    image: '/assets/blessures-lian-laya-ensemble.jpeg',
    images: [
      '/assets/blessures-lian-laya-ensemble.jpeg',
      '/assets/blessures-lian-front.jpeg',
      '/assets/blessures-lian-main-visage.jpeg',
      '/assets/blessures-laya-egratinure-1.jpeg',
      '/assets/blessures-laya-egratinure-2.jpeg',
    ],
    description: 'Deux maquillages de blessures : une plaie en demi-cœur sur la moitié du visage et une égratignure sur la pommette.',
    materials: 'Faux sang, sang coagulé, latex liquide',
    story: `J'ai maquillé ma sœur et ma cousine pour un shooting dans une ambiance tamisée. Pour ma sœur, j'ai réalisé une plaie qui prend la moitié du visage et forme un demi-cœur — un motif volontairement symbolique. Pour ma cousine, j'ai opté pour quelque chose de plus discret : une simple égratignure au niveau de la pommette. Les photos ont été prises dans une lumière douce et sombre pour renforcer l'atmosphère.`,
  },
  {
    id: 'bouteilles-peintes',
    title: 'Bouteilles de champagne décorées',
    category: 'Décoration',
    image: '/assets/bouteilles-collection.jpeg',
    images: [
      '/assets/bouteilles-collection.jpeg',
      '/assets/bouteille-verte-rose.jpeg',
    ],
    description: 'Bouteilles de champagne recyclées, peintes et décorées de paillettes, strass et dentelle.',
    materials: 'Bouteilles de champagne recyclées, peinture, strass, paillettes, dentelle',
    story: `À l'origine créées pour décorer l'anniversaire des 16 ans d'une amie, ces bouteilles ont eu tellement de succès auprès des invités que j'en ai réalisé d'autres dans différents coloris. Le principe reste le même : peindre la partie inférieure dans une couleur, la partie supérieure dans une autre, et marquer la délimitation avec un liseré de strass ou de dentelle. Les paillettes ajoutées sur le goulot apportent une touche festive. Chaque bouteille devient ainsi un objet décoratif unique.`,
  },
  {
    id: 'tresse-chignon',
    title: 'Tresses collées en chignon',
    category: 'Coiffure',
    image: '/assets/tresse-chignon-dos-1.jpeg',
    images: [
      '/assets/tresse-chignon-dos-1.jpeg',
      '/assets/tresse-chignon-dos-2.jpeg',
    ],
    description: 'Coiffure avec deux tresses collées partant du front et de la nuque, réunies en chignon.',
    materials: '',
    story: `J'ai divisé le crâne en deux sections, puis réalisé une tresse collée de chaque côté : l'une partant du front vers le centre du crâne, l'autre depuis la nuque. Les deux tresses se rejoignent pour former un chignon. Les tresses ont été volontairement travaillées avec du lâcher pour donner du volume, adapté à la texture des cheveux de la personne coiffée.`,
  },
  {
    id: 'bouche-cousue',
    title: 'Bouche cousue — damoiselle aux yeux bandés',
    category: 'Maquillage FX',
    image: '/assets/bouche-cousue-miroir.jpeg',
    images: [
      '/assets/bouche-cousue-miroir.jpeg',
    ],
    description: 'Maquillage FX : bouche cousue avec fils de fer et latex, yeux recouverts d\'un bandage ensanglanté.',
    materials: 'Bandage, fil de fer souple, latex liquide, fard gras, faux sang, sang coagulé',
    story: `Pour ce maquillage, j'ai simulé une bouche cousue sur ma sœur en appliquant du latex sur du papier mouchoir (jamais directement sur les lèvres) pour créer une base, puis j'y ai accroché de fins fils de fer recourbés pour imiter des points de suture. L'ensemble a été fixé au latex. Comme le papier modifiait légèrement le teint, j'ai utilisé du fond de teint pour harmoniser, même si la nuance n'était pas parfaite. Pour les yeux, un bandage enroulé autour du visage a servi de base, sur lequel j'ai appliqué du fard gras et quelques coulures de sang aux emplacements des yeux. La photo a été prise face à un miroir : dans le reflet, on voit ma sœur sans maquillage qui se regarde — un effet de contraste saisissant entre le réel et le maquillé.`,
  },
  {
    id: 'cloches-18ans',
    title: 'Cloches souvenir — 18 ans',
    category: 'Décoration',
    image: '/assets/cloches-18ans.jpeg',
    images: [
      '/assets/cloches-18ans.jpeg',
    ],
    description: 'Petites cloches décoratives avec bougie LED, plumes roses et chiffre 18 en mousse, offertes en souvenir aux invités.',
    materials: 'Cloches en verre, bougie LED, plumes colorées (nuances de rose), fil doré, mousse (type foam)',
    story: `Pour les 18 ans d'une amie, nous voulions offrir à chaque invité un petit souvenir à emporter. J'ai décoré des cloches en verre en plaçant à l'intérieur une bougie LED posée sur du fil doré, entourée de plusieurs plumes dans différentes nuances de rose. Accroché à chaque cloche, un chiffre "18" découpé dans de la mousse (type foam) et relié par une ficelle. Un cadeau à la fois délicat et personnalisé, que les invités pouvaient conserver comme décoration chez eux.`,
  },
  {
    id: 'alice-carte-2021',
    title: 'Alice au Pays des Merveilles — premier maquillage Halloween',
    category: 'Maquillage FX',
    image: '/assets/alice-carte-2021-costume.jpeg',
    images: [
      '/assets/alice-carte-2021-costume.jpeg',
    ],
    description: 'Maquillage Halloween 2021 : Alice avec une carte de la Reine de Cœur dans le front et une blessure sur la joue.',
    materials: 'Latex liquide, carte à jouer, faux sang, sang coagulé',
    story: `C'est le tout premier maquillage Halloween que j'ai réalisé, en 2021, pour ma sœur qui adore Alice au Pays des Merveilles. J'ai recréé l'illusion d'une carte — la Dame de Cœur — enfoncée dans le front, avec une blessure supplémentaire sur la joue pour renforcer l'effet. C'est ce maquillage qui m'a donné envie de continuer à explorer le maquillage FX chaque Halloween.`,
  },
  {
    id: 'main-os',
    title: 'Dos de main — os apparents',
    category: 'Maquillage FX',
    image: '/assets/main-os-alice-2021.jpeg',
    images: [
      '/assets/main-os-alice-2021.jpeg',
    ],
    description: 'Maquillage FX sur le dos de la main : peau lacérée laissant apparaître les os des doigts simulés en cotons-tiges.',
    materials: 'Latex liquide, cotons-tiges, faux sang, sang coagulé, fard gras',
    story: `Pour Halloween 2021, j'ai réalisé ce maquillage sur le dos de ma propre main. Les "os" des doigts sont simulés avec des cotons-tiges positionnés et recouverts de latex pour les intégrer à la peau. Des couches de latex ont ensuite été posées autour pour créer l'effet de chair déchirée, finalisées avec du faux sang et du sang coagulé pour le rendu réaliste. Un effet simple à réaliser mais très efficace visuellement.`,
  },
];